#include "corepss.h"
#include "core.h"
#include "densematrix.h"
#include "simulator.h"
#include "common.h"
#include <cmath>
#include <sstream>
#include <iomanip>

namespace NAMESPACE {

// ----------------------------------------------------------------
// PssParameters introspection
// ----------------------------------------------------------------

template<> int Introspection<PssParameters>::setup() {
    registerMember(driven);
    registerMember(tper);
    registerMember(tstab);
    registerMember(stabstep);
    registerMember(maxacfreq);
    registerMember(store);
    registerMember(write);
    registerNamedMember(stabilParams.ic, "ic");
    registerNamedMember(stabilParams.icmode, "icmode");
    registerNamedMember(stabilParams.write, "writestab");
    registerNamedMember(opParams.nodeset, "nodeset");
    return 0;
}
instantiateIntrospection(PssParameters);

PssCore::PssCore(
    OutputDescriptorResolver& parentResolver,
    PssParameters& params,
    Circuit& circuit,
    CommonData& commons,
    KluRealMatrix& jacobian,
    VectorRepository<double>& solution,
    VectorRepository<double>& states,
    OperatingPointCore& opCore,
    TranCore& stabilTran,
    PssTranCore& pssTran
) : AnalysisCore(parentResolver, circuit, commons),
    params(params),
    jacobian(jacobian),
    solution(solution),
    states(states),
    opCore_(opCore),
    stabilTran_(stabilTran),
    pssTran_(pssTran),
    T0_converged_(0.0)
{
}

// Don't need a destructor, outfile object is in other cores

// PSS core does not produce anything itself. 
// This is just a dummy override so this class is not abstract. 
bool PssCore::addDefaultOutputDescriptors(Status& s) {
    return true;
}

// Don't need descriptor resolution, core descriptors
// Output files are generated by stabilTran_ and pssTran_

// Don't need preMapping() and populateStructures()

// TODO: place all resize() calls here
bool PssCore::rebuild(Status& s) {
    return true;
}

bool PssCore::initializeOutputs(Id name, Status& s) {
    // Store the name for use when the output file is opened after convergence.
    // Do NOT open the pssTran_ raw file here: it must be opened only once,
    // after the Newton loop converges, so that intermediate shooting iterations
    // do not pollute the output.
    name_ = name;
    return true;
}

bool PssCore::finalizeOutputs(Status& s) {
    return pssTran_.finalizeOutputs(s);
}

bool PssCore::deleteOutputs(Id name, Status& s) {
    if (!params.write || Simulator::noOutput()) {
        return true;
    }
    // Cannot assume outfile is available
    auto fname = std::string(name)+".raw";
    if (std::filesystem::exists(fname)) {
        std::filesystem::remove(fname);
    }
    return true;
}

bool PssCore::storeState(size_t ndx) {
    auto& repo = coreStates.at(ndx);
    repo.solution.setTypeTag(OperatingPointCore::solutionTag);

    // Store current solution as annotated solution
    repo.solution.setNames(circuit);
    
    // Store solution in frequency domain (complex spectrum)
    repo.solution.setValues(solution.vector());
    
    // Store period
    repo.solution.setAuxReal(T0_converged_);

    // Stored state is coherent and valid
    repo.coherent = true;
    repo.valid = true;
    return true;
}

bool PssCore::restoreState(size_t ndx) {
    auto& state = coreStates.at(ndx);
    if (state.valid) {
        // State is valid
        continueState = &state;
        return true;
    } else { 
        // Nothing to restore, do not use continuation mode
        return false;
    }
}

// ----------------------------------------------------------------
// Stabilisation transient
// ----------------------------------------------------------------

// Shooting always uses forces for establishing starting point
// since PSS is so expensive forces do not incur significant overhead
// (only a few more NR iterations) compared to continueMode via soluton vector

// nodeset is passed to opCore_, ic is passed to stabilTran_ 
// Both are using the same Jacobian so preMapping()/populateStructutres() 
// of these two cores will take care of all the reuqired entries. 

// continuePrevious=1 (sweep, homotopy)
// No stabilisaiton transient
// - Use stored solution as nodeset in OP, use state slot 0 and continuePrevious=1
// 
// continuePrevious=0
// Stabilisation transient enabled (tstab>0)
// - Use ic parameter as IC in OP mode for stabilisation transient
//   Since it is already passed to stabilTran_, just run with icmode=op. 
// Stabilisation transient disabled, ic parameter given
// - Use ic parameter as nodeset with opCore_. 
//   Use it via state slot 2 and continuePrevious=1. 
// Stabilisation transient disabled, no ic parameter given
// - Ordinary opCore_ run with nodeset. 

// If we ever allow homotopy, move part of this to runSolver()
std::tuple<bool, double> PssCore::runStabilisation(bool continuePrevious) {
    auto& options = circuit.simulatorOptions().core();
    double period = 0;
    if (continuePrevious) {
        // Continue mode (sweep, homotopy)
        auto& opSlot = opCore_.coreState(0);
        if (
            continueState && continueState->valid &&
            continueState->solution.typeTag()==OperatingPointCore::solutionTag
        ) {
            // Valid state
            // Fill slot 2 of opCore_ with stored solution
            // Use abortOnError=true, any error is returned immediately
            if (!opCore_.solver().setForces(2, continueState->solution, true)) {
                setError(PssError::ForcesFailed);
                return std::make_tuple(false, period);
            }
            // Extract period from continueState
            period = continueState->solution.auxReal();
            // Default to value of tper
            if (period<=0) {
                period = params.tper;
            }
            // Continue state is spent after first use
            continueState = nullptr;
            // Disable nodesets. 
            opCore_.enableNodesets(false);
            // Enable UIC forces. 
            opCore_.solver().enableForces(2, true);
            // Run in continuePrevious=false mode. 
            bool opContinuePrevious = false;
            // Run operating point
            if (!opCore_.run(opContinuePrevious)) {
                setError(PssError::OpFailed);
                return std::make_tuple(false, period);
            }    
        } else {
            // No valid state, continue with whatever is in solution
            // Set period to tper
            period = params.tper;
            // Nothing to do
        }
    } else {
        // Ordinary mode, use stabiliation transient for determining first point of shooting
        // Extract period from ic
        if (params.stabilParams.ic.type()==Value::Type::String) {
            String& solutionName = params.stabilParams.ic.val<String>();
            if (solutionName.length()>0) {
                auto solPtr = circuit.storedSolution(solutionName);
                if (solPtr) {
                    // Found solution
                    period = solPtr->auxReal();
                }
            }
        }
        // Default to value of tper
        if (period<=0) {
            period = params.tper;
        }
        // Check for valid period (we need it)
        if (period<=0) {
            setError(PssError::TperInvalid);
            return std::make_tuple(false, period);
        }
        // Check parameters
        if (params.tstab>0 && params.tstab < 10.0 * params.tper) {
            Simulator::wrn() << "PSS: Tstab < 10 * Tper. Oscillator may not have settled.\n";
        }
        if (params.stabstep>0) {
            // stabstep given
            params.stabilParams.step = params.stabstep;
        } else {
            // no stabstep
            // TODO: 1000 is a bit excessive?
            params.stabilParams.step = period / options.pss_minpts;
        }
        params.stabilParams.stop    = params.tstab;
        params.stabilParams.maxstep = params.stabilParams.step;
        params.stabilParams.start   = 0.0;
        if (params.maxacfreq > 0) {
            double effMaxacfreq = std::max(params.maxacfreq, 40.0 / period);
            double hmax = std::min(params.stabilParams.maxstep, 1.0 / (2.0 * effMaxacfreq));
            params.stabilParams.maxstep = hmax;
            params.stabilParams.step    = std::min(params.stabilParams.step, hmax);
        }
        // Use stabilTran_ with continuePrevious=false
        if (!stabilTran_.run(false)) {
            setError(PssError::StabilisationTranFailed);
            return std::make_tuple(false, period);
        }
    }
    
    return std::make_tuple(true, period);
}


// ----------------------------------------------------------------
// One-period shoot
// ----------------------------------------------------------------

bool PssCore::runShoot(double T0) {
    auto& options = circuit.simulatorOptions().core();
    params.shootParams.stop    = T0;
    params.shootParams.step    = T0 / options.pss_minpts;
    params.shootParams.maxstep = T0 / options.pss_minpts;
    params.shootParams.start   = 0.0;
    if (params.maxacfreq > 0) {
        double effMaxacfreq = std::max(params.maxacfreq, 40.0 / T0);
        double hmax = std::min(params.shootParams.maxstep, 1.0 / (2.0 * effMaxacfreq));
        params.shootParams.maxstep = hmax;
        params.shootParams.step    = std::min(params.shootParams.step, hmax);
    }
    
    if (!pssTran_.run(false)) {
        setError(PssError::ShootingTranFailed);
        return false;
    }
    return true;
}


// ----------------------------------------------------------------
// Sensitivity integration
// ----------------------------------------------------------------

bool PssCore::runSensitivity(
    DenseMatrix<double>& PhiT,
    Vector<double>&      PsiT
) {
    auto n = circuit.unknownCount();
    if (!params.driven) {
        Vector<double> x_laststep(n, 0.0);
        for (int i=0; i < n; i++)
            x_laststep[i] = solution.pastVector()[i+1] - solution.vector()[i+1];
        if (!pssTran_.integrateAugmentedSensitivity(PhiT, PsiT, x_laststep)) {
            setError(PssError::SensitivityFailed);
            return false;
        }
    } else {
        if (!pssTran_.integrateSensitivity(PhiT)) {
            setError(PssError::SensitivityFailed);
            return false;
        }
    }

    return true;
}


// ----------------------------------------------------------------
// Phase constraint
// ----------------------------------------------------------------

void PssCore::computePhaseConstraint(
    const Vector<double>& x0,
    double T0,
    const Vector<double>& PsiT,
    Vector<double>& alpha
) {
    // alpha is the phase-pinning vector. The augmented Newton row
    //   alpha^T * dx0 = 0
    // constrains the correction dx0 to be perpendicular to alpha, so the
    // Newton step does not move along the phase direction (the null space of
    // (I - PhiT)). alpha must not be in the image of (I - PhiT), so it should
    // be proportional to xdot_s(t0), the circuit velocity at t0.
    //
    // From the circuit DAE: g(x) + C(x)*xdot = 0, so
    //   xdot_s(t0) = -C(x0)^{-1} * g(x0)
    //
    // PsiT = alphaLast * Alr^{-1} * g(xT) ≈ -xdot_s(t0) (same approximation
    // as the period sensitivity vector: C^{-1} ≈ alphaLast * Alr^{-1}).
    // Using PsiT as alpha avoids extra evalAndLoad calls and is consistent.
    // Normalised to unit length for numerical conditioning.

    auto n = circuit.unknownCount();
    alpha.assign(n + 1, 0.0);

    double norm = 0.0;
    for (decltype(n) i = 1; i <= n; i++) {
        norm += PsiT[i] * PsiT[i];
    }
    norm = std::sqrt(norm);

    if (norm > 0.0) {
        for (decltype(n) i = 1; i <= n; i++) {
            alpha[i] = PsiT[i] / norm;
        }
    } else {
        if (circuit.simulatorOptions().core().pss_debug) {
            Simulator::dbg() << "PsiT is zero\n";
        }
        // PsiT is zero (purely resistive circuit or degenerate first step).
        // Fall back to pinning the first unknown.
        if (n >= 1) {
            alpha[1] = 1.0;
        }
    }
}

// ----------------------------------------------------------------
// Main Newton loop
// ----------------------------------------------------------------

CoreCoroutine PssCore::coroutine(bool continuePrevious) {
    clearError();

    // Disable shooting transient output
    params.shootParams.write = 0;

    auto& options = circuit.simulatorOptions().core();
    auto debug = options.pss_debug;

    auto n = circuit.unknownCount();

    /// TODO: Move to private class members. Size correctly during rebuild.
    Vector<double>      PsiT;
    Vector<double>      Fp(n + 1, 0.0);
    Vector<double>      alpha(n + 1, 0.0);
    DenseMatrix<double> Jp(n + 1, n + 1);

    Int    iterIndex  = 0;
    double worstRatio = 0.0;
    Vector<double>  x0;
    Vector<double>  xT;
    double          T0;

    T0_converged_ = 0.0;
    x0_converged_.clear();
    bool converged = false;

    std::stringstream ss;
    ss << std::scientific << std::setprecision(4);

    // Stabilisation is run if tstab>0, stabstep if>0 must be <tstab
    if (params.tstab>0 && params.stabstep>0 && params.stabstep>=params.tstab) {
        setError(PssError::StabstepInvalid);
        co_yield CoreState::Aborted;
    }

    // Stabilisation transient, determine initial period from parameters and stored solution
    auto [okStabil, period] = runStabilisation(continuePrevious);
    if (!okStabil) {
        co_yield CoreState::Aborted;
    }
    // Require tper>0
    if(period <= 0) {
        setError(PssError::TperInvalid);
        co_yield CoreState::Aborted;
    }

    // Disable nodesets in opCore_
    opCore_.enableNodesets(false);

    // x_0^(0) is the state of the circuit after running the stabilisation transient
    x0 = solution.vector();
    T0 = period;

    // Continue mode
    //   Have stored solution
    //     Take T0 from solution
    //   No stored solution
    //     Use whatever is in T0
    // Ordinary mode
    //   


    // Obtain x_T^(0) by running a transient simulation for T_0 seconds
    solution.vector() = x0;
    pssTran_.setShootIC(x0);
    if (!pssTran_.clearTrajectory(T0)) {
        setError(PssError::ShootingTranFailed);
        co_yield CoreState::Aborted;
    }
    if (!runShoot(T0)) {
        // runShoot() sets the error code
        co_yield CoreState::Aborted;
    }
    xT = solution.vector();

    // PSS-SHOOT main loop (outer NR)
    while (iterIndex <= options.pss_itl) {
        if (debug>0){
            ss.str(""); 
            ss << "PSS: shoot l=" << iterIndex << "\n";
            ss << "\tx0=[";
            auto n = circuit.unknownCount();
            for (decltype(n) i = 1; i <= n; i++) ss << " " << x0[i];
            ss << " ]\n" << "\txT=[";
            for (decltype(n) i = 1; i <= n; i++) ss << " " << xT[i];
            ss << " ]\n";
            if (!params.driven) {
                ss << "\tT0=" << T0 << "\n";
            }
            Simulator::dbg() << ss.str();
        }

        // Obtain sensitivity matrices
        if (!runSensitivity(phiT_, PsiT)) {
            // Error was set by runSensitivity()
            co_yield CoreState::Aborted;
        }
        if (debug>0) {
            ss.str(""); 
            auto n = circuit.unknownCount();
            ss << "\tPhiT=\n";
            for (decltype(n) i = 0; i < n; i++) {
                ss << "\t  [ ";
                for (decltype(n) j = 0; j < n; j++) ss << phiT_.at(i, j) << " ";
                ss << "]\n";
            }
            if(!params.driven) {
                ss << "\tPsiT=[ ";
                for (decltype(n) i = 1; i <= n; i++) ss << PsiT[i] << " ";
                ss << "]\n";
            }
            Simulator::dbg() << ss.str();
        }

        // Compute the residual
        for (decltype(n) i = 0; i < n; i++) {
            // skip the bucket at x[0]
            Fp[i] = x0[i + 1] - xT[i + 1];
        }

        // Jacobian: I - PhiT
        for (decltype(n) i = 0; i < n; i++) {
            for (decltype(n) j = 0; j < n; j++) {
                Jp.at(i, j) = (i == j ? 1.0 : 0.0) - phiT_.at(i, j);
            }
        }

        // Compute phase constraint for autonomous circuits
        /// TODO: rewrite computePhaseConstraint without weird approximations
        if (!params.driven){
            computePhaseConstraint(x0, T0, PsiT, alpha);
            if (debug>0){
                ss.str(""); 
                ss << "\talpha=[ ";
                for (decltype(n) i = 0; i <= n; i++) ss << alpha[i] << " ";
                ss << "]\n";
                Simulator::dbg() << ss.str();
            }
            // Add alpha^Tx_0 to the Fp map
            Fp[n] = 0;
            //for (decltype(n) i = 0; i <= n; i++) Fp[n] += alpha[i] * x0[i];
            // Augment the Jacobian
            // Right column: PsiT
            for (decltype(n) i = 0; i < n; i++) Jp.at(i, n) = -PsiT[i + 1];
            // Bottom row: alpha^T
            for (decltype(n) j = 0; j < n; j++) Jp.at(n, j) = alpha[j + 1];
        }
        // If the circuit is driven, make sure Jp is not singular by setting the corner to 1
        Jp.at(n, n) = params.driven ? 1.0 : 0.0;

        // Solve the Newton step
        VectorView<double> rhsView(Fp);
        if (!Jp.destructiveSolve(rhsView)) {
             setError(PssError::SingularJacobian);
             co_yield CoreState::Aborted;
        }
        // Update x0 and T0
        for (decltype(n) i = 0; i < n; i++) x0[i + 1] -= rhsView[i];
        T0 -= params.driven ? 0.0 : rhsView[n];

        // Get new xT
        solution.vector() = x0;
        pssTran_.setShootIC(x0);
        if (!pssTran_.clearTrajectory(T0)) {
            setError(PssError::ShootingTranFailed);
            co_yield CoreState::Aborted;
        }
        if (!runShoot(T0)) {
            // runShoot() sets the error code
            co_yield CoreState::Aborted;
        }
        xT = solution.vector();

        // Convergence check: per-unknown shooting residual vs SPICE delta tolerance.
        // A (used): tol[i] = pss_tolscale * max(|x0[i]|*reltol, abstol[i]) -- matches OP/TRAN
        //   checkDelta; scales with signal magnitude so large/small nodes converge proportionally.
        // pss_tolscale should be >=1. One cannot expect stricter tolerance from PSS 
        // than from underlying op/tran. 
        bool shootConverged = true;
        worstRatio = 0.0;
        for (decltype(n) i = 1; i <= n; i++) {
            double tol = options.pss_tolscale *
                         std::max(std::fabs(x0[i]) * options.reltol, commons.unknown_abstol[i]);
            double ratio = std::fabs(x0[i] - xT[i]) / tol;
            if (ratio > worstRatio) worstRatio = ratio;
            if (ratio > 1.0) shootConverged = false;
        }
        if (debug>0){
            ss.str("");
            ss << "\tworst residual ratio= " << worstRatio << "\n";
            Simulator::dbg() << ss.str();
        }

        if (shootConverged) {
            converged = true;
            break;
        } else {
            iterIndex++;
        }
    } // end PSS-SHOOT main loop
    
    if (!converged) {
        setError(PssError::NoConvergence);
        co_yield CoreState::Aborted;
    }

    if (converged && params.store.length()>0) {
        auto& sol = circuit.newStoredSolution(params.store);
        sol.setTypeTag(OperatingPointCore::solutionTag);
        sol.setNames(circuit);
        sol.setValues(solution.vector());
        sol.setAuxReal(T0);
    }

    if (debug>0) {
        Simulator::dbg() << "PSS analysis finshed.\n";
        ss.str("");
        ss << "Converged in " << iterIndex + 1 << " iterations.\n";
        ss << "Final worst residual ratio = " << worstRatio << "\n";
        Simulator::dbg() << ss.str();
    }

    // Enable writing for last run of shooting transient
    params.shootParams.write = params.write;
    
    solution.vector() = x0;
    pssTran_.setShootIC(x0);
    if (!pssTran_.clearTrajectory(T0)) {
        setError(PssError::ShootingTranFailed);
        co_yield CoreState::Aborted;
    }
    pssTran_.enableTrajectoryCapture();
    if (!runShoot(T0)) {
        co_yield CoreState::Aborted;
    }

    // Integrate Omega backward using captured trajectory
    if (!pssTran_.integrateAdjointMonodromy(omegaT_)) {
        setError(PssError::AdjointFailed);
        co_yield CoreState::Aborted;
    
    }

    if (debug>0) {
        ss.str(""); 
        auto n = circuit.unknownCount();
        ss << "-- Monodromy matrices --\n";
        ss << "\tPhi(T,0) =\n";
        for (decltype(n) i = 0; i < n; i++) {
            ss << "\t  [ ";
            for (decltype(n) j = 0; j < n; j++) ss << phiT_.at(i, j) << " ";
            ss << "]\n";
        }
        ss << "\tOmega(T,0) =\n";
        for (decltype(n) i = 0; i < n; i++) {
            ss << "\t  [ ";
            for (decltype(n) j = 0; j < n; j++) ss << omegaT_.at(i, j) << " ";
            ss << "]\n";
        }
        Simulator::dbg() << ss.str();
    }
    
    x0_converged_ = x0;
    T0_converged_ = T0;
    co_yield CoreState::Finished;
    
}

bool PssCore::run(bool continuePrevious) {
    auto c = coroutine(continuePrevious);
    bool ok = true;
    while (!c.done()) {
        if (c.resume() == CoreState::Aborted) {
            ok = false;
            break;
        }
    }
    return ok;

}

bool PssCore::formatError(Status& s) const {
    switch (lastPssError) {
        case PssError::NoConvergence:
            s.set(Status::Analysis,
                  "PSS failed to converge in " +
                  std::to_string(circuit.simulatorOptions().core().pss_itl) + " iterations.");
            return false;
        case PssError::SensitivityFailed:
            // Format pssTran_ error, add message
            pssTran_.formatError(s);
            s.extend("PSS sensitivity integration failed.");
            return false;
        case PssError::AdjointFailed:
            s.set(Status::Analysis, "Adjoint monodromy computation failed.");
            return false;
        case PssError::LinearSolveFailed:
            s.set(Status::Analysis, "PSS Newton linear solve failed.");
            return false;
        case PssError::OutputError:
            s.set(Status::Analysis, "PSS output error.");
            return false;
        case PssError::TperInvalid:
            s.set(Status::Analysis, "Period should be >0.");
            return false;
        case PssError::SingularJacobian:
            s.set(Status::Analysis, "Singular Jacobian.");
            return false;
        case PssError::StabstepInvalid:
            s.set(Status::Analysis, "Stabilization timestep must be smaller than the period.");
            return false;
        case PssError::StabilisationTranFailed:
            stabilTran_.formatError(s);
            s.extend("PSS stabilisation transient failed.");
            return false;
        case PssError::OpFailed:
            opCore_.formatError(s);
            s.extend("PSS operating point failed.");
            return false;
        case PssError::ShootingTranFailed:
            pssTran_.formatError(s);
            s.extend("PSS transient failed.");
            return false;
        case PssError::ForcesFailed: {
            auto nr = UnknownNameResolver(circuit);
            opCore_.solver().formatError(s, &nr);
            s.extend("Failed to set forces.");
            return false;
        }
        default:
            return true;
    }
}

void PssCore::dump(std::ostream& os) const {
    AnalysisCore::dump(os);
    os << "  Converged period: " << T0_converged_ << " s\n";
    os << "  Converged frequency: "
       << (T0_converged_ > 0 ? 1.0 / T0_converged_ : 0.0) << " Hz\n";
}

} // namespace NAMESPACE
