#include "corepss.h"
#include "core.h"
#include "densematrix.h"
#include "simulator.h"
#include "common.h"
#include <cmath>
#include <sstream>
#include <iomanip>

namespace NAMESPACE {

// ----------------------------------------------------------------
// PssParameters introspection
// ----------------------------------------------------------------

template<> int Introspection<PssParameters>::setup() {
    registerMember(driven);
    registerMember(tper);
    registerMember(tstab);
    registerMember(stabstep);
    registerMember(icmode);
    registerMember(maxacfreq);
    registerMember(store);
    registerMember(write);
    registerNamedMember(stabilParams.ic, "ic");
    registerNamedMember(stabilParams.write, "writestab");
    registerNamedMember(opParams.nodeset, "nodeset");
    return 0;
}
instantiateIntrospection(PssParameters);

PssCore::PssCore(
    OutputDescriptorResolver& parentResolver,
    PssParameters& params,
    Circuit& circuit,
    CommonData& commons,
    KluRealMatrix& jacobian,
    VectorRepository<double>& solution,
    VectorRepository<double>& states,
    OperatingPointCore& opCore,
    TranCore& stabilTran,
    PssTranCore& pssTran
) : AnalysisCore(parentResolver, circuit, commons),
    params(params),
    jacobian(jacobian),
    solution(solution),
    states(states),
    opCore_(opCore),
    stabilTran_(stabilTran),
    pssTran_(pssTran),
    T0_converged_(0.0)
{
    // Slot 3 is for ICs in continuation mode
    opCore_.solver().resizeForces(4);
    stabilTran_.solver().resizeForces(4);
}

// Don't need a destructor, outfile object is in other cores

// PSS core does not produce anything itself. 
// This is just a dummy override so this class is not abstract. 
bool PssCore::addDefaultOutputDescriptors(Status& s) {
    return true;
}

// Don't need descriptor resolution, core descriptors
// Output files are generated by stabilTran_ and pssTran_

// Don't need preMapping() and populateStructures()

bool PssCore::rebuild(Status& s) {
    auto& options = circuit.simulatorOptions().core();
    // Tran IC forces
    stabilTran_.solver().setForcesFactor(3, options.nr_force);
    // OP IC forces
    opCore_.solver().setForcesFactor(3, options.nr_force);

    auto n = circuit.unknownCount();
    Fp.resize(n+1);
    alpha.resize(n);
    // We are going to solve a linear system with this matrix. 
    // Make it column major. 
    Jp.resize(n+1, n+1, DenseMatrix<double>::Major::Column);
    x0.resize(n+1);
    xT.resize(n+1);

    return true;
}

bool PssCore::initializeOutputs(Id name, Status& s) {
    // Store the name for use when the output file is opened after convergence.
    // Do NOT open the pssTran_ raw file here: it must be opened only once,
    // after the Newton loop converges, so that intermediate shooting iterations
    // do not pollute the output.
    name_ = name;
    return true;
}

bool PssCore::finalizeOutputs(Status& s) {
    return pssTran_.finalizeOutputs(s);
}

bool PssCore::deleteOutputs(Id name, Status& s) {
    if (!params.write || Simulator::noOutput()) {
        return true;
    }
    // Cannot assume outfile is available
    auto fname = std::string(name)+".raw";
    if (std::filesystem::exists(fname)) {
        std::filesystem::remove(fname);
    }
    return true;
}

bool PssCore::storeState(size_t ndx, bool storeDetails) {
    auto& repo = coreStates.at(ndx);
    repo.solution.setTypeTag(OperatingPointCore::solutionTag);

    // Store current solution as annotated solution
    if (storeDetails) {
        repo.solution.setNames(circuit);
    } else {
        repo.solution.clearNames();
    }
    
    // Store time domain solution
    repo.solution.setValues(solution.vector());
    
    // Store period
    repo.solution.setAuxReal(T0_converged_);

    // Stored state is coherent and valid
    repo.coherent = true;
    repo.valid = true;
    return true;
}

bool PssCore::restoreState(size_t ndx) {
    auto& state = coreStates.at(ndx);
    if (state.valid) {
        // State is valid
        continueState = &state;
        return true;
    } else { 
        // Nothing to restore, do not use continuation mode
        return false;
    }
}

// ----------------------------------------------------------------
// Stabilisation transient
// ----------------------------------------------------------------

// Shooting always uses forces for establishing starting point
// since PSS is so expensive forces do not incur significant overhead
// (only a few more NR iterations) compared to continueMode via soluton vector

// nodeset is passed to opCore_, ic is passed to stabilTran_ 
// Both are using the same Jacobian so preMapping()/populateStructutres() 
// of these two cores will take care of all the reuqired entries. 

void PssCore::clampStepToMaxacfreq(TranParameters& tp, double period) const {
    if (params.maxacfreq > 0) {
        double effMaxacfreq = std::max(params.maxacfreq, 40.0 / period);
        double hmax = std::min(tp.maxstep, 1.0 / (2.0 * effMaxacfreq));
        tp.maxstep = hmax;
        tp.step    = std::min(tp.step, hmax);
    }
}

void PssCore::prepareStabilisation(double period) {
    auto& options = circuit.simulatorOptions().core();
    if (params.stabstep>0) {
        // stabstep given
        params.stabilParams.step = params.stabstep;
    } else {
        // no stabstep
        params.stabilParams.step = period / options.pss_minpts;
    }
    params.stabilParams.stop    = params.tstab;
    params.stabilParams.maxstep = params.stabilParams.step;
    params.stabilParams.start   = 0.0;

    clampStepToMaxacfreq(params.stabilParams, period);
}

// If we ever allow homotopy, move part of this to runSolver()
std::tuple<bool, double> PssCore::runStabilisation(bool continuePrevious) {
    auto& options = circuit.simulatorOptions().core();
    double period = 0;
    if (continuePrevious) {
        // Continue mode (sweep, homotopy)
        // Stored solution has no delta forces. 
        if (
            continueState && 
            continueState->valid && continueState->coherent &&
            continueState->solution.typeTag()==OperatingPointCore::solutionTag &&
            continueState->solution.values().size()==circuit.unknownCount()+1
        ) {
            // Valid coherent state
            // Extract period
            period = params.tper;
            // Default to value from stored solution
            if (period<=0) {
                // Default to value from stored solution
                period = continueState->solution.auxReal();    
            }
            // Check for valid period (we need it)
            if (period<=0) {
                setError(PssError::TperInvalid);
                return std::make_tuple(false, period);
            }
            // Put it in forces slot 3 of stabilTran_
            if (!stabilTran_.solver().setForces(3, continueState->solution, options.strictforce)) {
                // Abort on error if strictforce is set
                if (options.strictforce) {
                    setError(PssError::ForcesFailed);
                    return std::make_tuple(false, period);
                }
                Simulator::wrn() << "Warning, setting IC forces from previous state failed.\n";
                stabilTran_.solver().forces(3).clear();
            }
            // Write it to solution
            solution.vector() = stabilTran_.solver().forces(3).unknownValue_;
        } else if (
            continueState && continueState->valid && 
            continueState->solution.typeTag()==OperatingPointCore::solutionTag
        ) {
            // Valid state, not coherent
            // Extract period
            period = params.tper;
            // Default to value of tper
            if (period<=0) {
                // Default to value from stored solution
                period = continueState->solution.auxReal();    
            }
            // Check for valid period (we need it)
            if (period<=0) {
                setError(PssError::TperInvalid);
                return std::make_tuple(false, period);
            }
            // Put it in forces slot 3 of opCore_, op mode
            if (!opCore_.solver().setForces(3, continueState->solution, options.strictforce)) {
                // Abort on error if strictforce is set
                if (options.strictforce) {
                    setError(PssError::ForcesFailed);
                    return std::make_tuple(false, period);
                }
                Simulator::wrn() << "Warning, setting IC forces from previous state failed.\n";
                opCore_.solver().forces(3).clear();
            }
            // Set ic foces slot to 3
            stabilTran_.setIcForcesSlot(3);
            // Do a stabilisation transient using icmode=op
            params.stabilParams.icmode = TranCore::icmodeOp;
            prepareStabilisation(period);
            // Run stabilTran_ with continuePrevious=false
            if (!stabilTran_.run(false)) {
                setError(PssError::StabilisationTranFailed);
                return std::make_tuple(false, period);
            }
            // Set ic forces slot to 2 (back to normal)
            stabilTran_.setIcForcesSlot(2);
            // Disable slot 3
            stabilTran_.solver().enableForces(3, false); 
        } else {
            // No valid state, continue with whatever is in solution
            // Set period to tper
            period = params.tper;
            // Check for valid period (we need it)
            if (period<=0) {
                setError(PssError::TperInvalid);
                return std::make_tuple(false, period);
            }
            // Nothing to do
        }
    } else {
        // Ordinary mode, use stabiliation transient for determining first point of shooting
        // Extract period from ic
        period = params.tper;
        if (params.stabilParams.ic.type()==Value::Type::String) {
            String& solutionName = params.stabilParams.ic.val<String>();
            if (solutionName.length()>0) {
                auto solPtr = circuit.storedSolution(solutionName);
                if (solPtr && solPtr->typeTag()==OperatingPointCore::solutionTag && period<=0) {
                    // Default to value from stored solution
                    period = solPtr->auxReal();
                }
            }
        }
        // Check for valid period (we need it)
        if (period<=0) {
            setError(PssError::TperInvalid);
            return std::make_tuple(false, period);
        }
        // Check parameters
        if (params.tstab>0 && params.tstab < 10.0 * params.tper) {
            Simulator::wrn() << "PSS: Tstab < 10 * Tper. Oscillator may not have settled.\n";
        }
        params.stabilParams.icmode = params.icmode;
        prepareStabilisation(period);
        // Run stabilTran_ with continuePrevious=false
        if (!stabilTran_.run(false)) {
            setError(PssError::StabilisationTranFailed);
            return std::make_tuple(false, period);
        }
    }
    
    return std::make_tuple(true, period);
}


// ----------------------------------------------------------------
// One-period shoot
// ----------------------------------------------------------------

bool PssCore::runShoot(double T0) {
    auto& options = circuit.simulatorOptions().core();
    params.shootParams.stop    = T0;
    params.shootParams.step    = T0 / options.pss_minpts;
    params.shootParams.maxstep = T0 / options.pss_minpts;
    params.shootParams.start   = 0.0;

    clampStepToMaxacfreq(params.shootParams, T0);


    if (!pssTran_.run(false)) {
        setError(PssError::ShootingTranFailed);
        return false;
    }

    // Psi_T (period sensitivity) is only needed for the autonomous phase
    // condition/Jacobian column. Computed once per shoot, here, rather than
    // at every accepted step inside PssTranCore - see pss.md, "Computing Psi_T".
    if (!params.driven && !pssTran_.computePsiT()) {
        setError(PssError::SensitivityFailed);
        return false;
    }
    return true;
}


// ----------------------------------------------------------------
// Phase constraint
// ----------------------------------------------------------------

void PssCore::computePhaseConstraint(
    const Vector<double>& x0,
    const Vector<double>& x1,
    double h0,
    Vector<double>& alpha
) {
    // alpha is the phase-pinning vector. The augmented Newton row
    //   alpha^T * dx0 = 0
    // constrains the correction dx0 to be perpendicular to alpha, so the
    // Newton step does not move along the phase direction (the null space of
    // (I - PhiT)). alpha must not be in the image of (I - PhiT), so it should
    // be proportional to xdot_s(t0), the circuit velocity at t0.
    //
    // Estimated by a forward finite difference between the first two points
    // of the shoot itself (pss.md, "Choosing alpha"):
    //   alpha ~= (x1 - x0) / h0
    // This needs no extra evalAndLoad call and carries no periodicity
    // assumption, unlike reusing PsiT (a t=T quantity, only equal to
    // xdot_s(0) at convergence, and even then only up to the O(h)
    // discretization error of the last step).
    // Normalised to unit length for numerical conditioning.

    auto n = circuit.unknownCount();
    alpha.assign(n, 0.0);

    double norm = 0.0;
    for (decltype(n) i = 0; i < n; i++) {
        double d = (x1[i + 1] - x0[i + 1]) / h0;
        alpha[i] = d;
        norm += d * d;
    }
    norm = std::sqrt(norm);

    if (norm > 0.0) {
        for (decltype(n) i = 0; i < n; i++) {
            alpha[i] /= norm;
        }
    } else {
        if (circuit.simulatorOptions().core().pss_debug) {
            Simulator::dbg() << "x1-x0 is zero, cannot estimate phase velocity\n";
        }
        // Degenerate first step (e.g. purely resistive circuit).
        // Fall back to pinning the first unknown.
        if (n >= 1) {
            alpha[0] = 1.0;
        }
    }
}

// ----------------------------------------------------------------
// Main Newton loop
// ----------------------------------------------------------------

CoreCoroutine PssCore::coroutine(bool continuePrevious) {
    clearError();

    // Disable shooting transient output
    params.shootParams.write = 0;

    auto& options = circuit.simulatorOptions().core();
    auto debug = options.pss_debug;

    auto n = circuit.unknownCount();

    zero(Fp);
    zero(alpha);
    Jp.zero();

    Int    iterIndex  = 0;
    double worstRatio = 0.0;
    double          T0;

    T0_converged_ = 0.0;
    x0_converged_.clear();
    bool converged = false;

    std::stringstream ss;
    ss << std::scientific << std::setprecision(4);

    // Stabilisation is run if tstab>0, if stabstep>0 it must be <tstab
    if (params.stabstep<0 ||
        (params.tstab>0 && params.stabstep>0 && params.stabstep>=params.tstab)
    ) {
        setError(PssError::StabstepInvalid);
        co_yield CoreState::Aborted;
    }

    // Stabilisation transient, determine initial period from parameters and stored solution
    auto [okStabil, period] = runStabilisation(continuePrevious);
    if (!okStabil) {
        co_yield CoreState::Aborted;
    }
    // Require tper>0
    if(period <= 0) {
        setError(PssError::TperInvalid);
        co_yield CoreState::Aborted;
    }

    // x_0^(0) is the state of the circuit after running the stabilisation transient
    x0 = solution.vector();
    T0 = period;

    // Continue mode
    //   Have stored solution
    //     Take T0 from solution
    //   No stored solution
    //     Use whatever is in T0
    // Ordinary mode
    //   


    // Obtain x_T^(0) by running a transient simulation for T_0 seconds
    solution.vector() = x0;
    pssTran_.setShootIC(x0);
    if (!pssTran_.clearTrajectory()) {
        setError(PssError::ShootingTranFailed);
        co_yield CoreState::Aborted;
    }
    if (!runShoot(T0)) {
        // runShoot() sets the error code
        co_yield CoreState::Aborted;
    }
    xT = solution.vector();

    // PSS-SHOOT main loop (outer NR)
    while (iterIndex < options.pss_itl) {
        if (debug>0){
            ss.str(""); 
            ss << "PSS: shoot l=" << iterIndex << "\n";
            ss << "\tx0=[";
            auto n = circuit.unknownCount();
            for (decltype(n) i = 1; i <= n; i++) ss << " " << x0[i];
            ss << " ]\n" << "\txT=[";
            for (decltype(n) i = 1; i <= n; i++) ss << " " << xT[i];
            ss << " ]\n";
            if (!params.driven) {
                ss << "\tT0=" << T0 << "\n";
            }
            Simulator::dbg() << ss.str();
        }

        // Obtain sensitivity matrices
        if (!pssTran_.phiValid()) {
            setError(PssError::SensitivityFailed);
            co_yield CoreState::Aborted;
        }
        auto& tmpPhiT = pssTran_.phiCurrent();
        if (debug>0) {
            ss.str(""); 
            auto n = circuit.unknownCount();
            ss << "\tPhiT=\n";
            for (decltype(n) i = 0; i < n; i++) {
                ss << "\t  [ ";
                for (decltype(n) j = 0; j < n; j++) ss << tmpPhiT.at(i, j) << " ";
                ss << "]\n";
            }
            if(!params.driven) {
                auto& tmpPsiT = pssTran_.psiCurrent();
                ss << "\tPsiT=[ ";
                for (decltype(n) i = 0; i < n; i++) ss << tmpPsiT[i] << " ";
                ss << "]\n";
            }
            Simulator::dbg() << ss.str();
        }

        // Compute the residual
        for (decltype(n) i = 0; i < n; i++) {
            // skip the bucket at x[0]
            Fp[i] = x0[i + 1] - xT[i + 1];
        }

        // Jacobian: I - PhiT
        for (decltype(n) i = 0; i < n; i++) {
            for (decltype(n) j = 0; j < n; j++) {
                Jp.at(i, j) = (i == j ? 1.0 : 0.0) - tmpPhiT.at(i, j);
            }
        }

        // Compute phase constraint for autonomous circuits
        if (!params.driven){
            auto& tmpPsiT = pssTran_.psiCurrent();
            computePhaseConstraint(x0, pssTran_.firstStepX(), pssTran_.firstStepH(), alpha);
            if (debug>0){
                ss.str("");
                ss << "\talpha=[ ";
                for (decltype(n) i = 0; i < n; i++) ss << alpha[i] << " ";
                ss << "]\n";
                Simulator::dbg() << ss.str();
            }
            // Add alpha^Tx_0 to the Fp map
            Fp[n] = 0;
            // Residual of the phase condition equation is 0 because
            // we are forcing orthogonality of the solver step. 
            // Augment the Jacobian
            // Right column: PsiT
            for (decltype(n) i = 0; i < n; i++) Jp.at(i, n) = -tmpPsiT[i];
            // Bottom row: alpha^T
            for (decltype(n) j = 0; j < n; j++) Jp.at(n, j) = alpha[j];
        }
        // If the circuit is driven, make sure Jp is not singular by setting the corner to 1
        Jp.at(n, n) = params.driven ? 1.0 : 0.0;

        // Solve the Newton step
        VectorView<double> rhsView(Fp);
        if (!Jp.destructiveSolve(rhsView)) {
             setError(PssError::SingularJacobian);
             co_yield CoreState::Aborted;
        }
        // Update x0 and T0
        for (decltype(n) i = 0; i < n; i++) x0[i + 1] -= rhsView[i];
        T0 -= params.driven ? 0.0 : rhsView[n];

        // Get new xT
        solution.vector() = x0;
        pssTran_.setShootIC(x0);
        if (!pssTran_.clearTrajectory()) {
            setError(PssError::ShootingTranFailed);
            co_yield CoreState::Aborted;
        }
        if (!runShoot(T0)) {
            // runShoot() sets the error code
            co_yield CoreState::Aborted;
        }
        xT = solution.vector();

        // Convergence check: per-unknown shooting residual vs SPICE delta tolerance.
        // A (used): tol[i] = pss_tolscale * max(|x0[i]|*reltol, abstol[i]) -- matches OP/TRAN
        //   checkDelta; scales with signal magnitude so large/small nodes converge proportionally.
        // pss_tolscale should be >=1. One cannot expect stricter tolerance from PSS 
        // than from underlying op/tran. 
        bool shootConverged = true;
        worstRatio = 0.0;
        for (decltype(n) i = 1; i <= n; i++) {
            double tol = options.pss_tolscale *
                         std::max(std::fabs(x0[i]) * options.reltol, commons.unknown_abstol[i]);
            double ratio = std::fabs(x0[i] - xT[i]) / tol;
            if (ratio > worstRatio) worstRatio = ratio;
            if (ratio > 1.0) shootConverged = false;
        }
        if (debug>0){
            ss.str("");
            ss << "\tworst residual ratio= " << worstRatio << "\n";
            Simulator::dbg() << ss.str();
        }

        if (shootConverged) {
            converged = true;
            break;
        } else {
            iterIndex++;
        }
    } // end PSS-SHOOT main loop
    
    if (!converged) {
        setError(PssError::NoConvergence);
        co_yield CoreState::Aborted;
    }

    // Store converged monodromy
    phiT_ = pssTran_.phiCurrent();

    if (converged && params.store.length()>0) {
        auto& sol = circuit.newStoredSolution(params.store);
        sol.setTypeTag(OperatingPointCore::solutionTag);
        sol.setNames(circuit);
        sol.setValues(solution.vector());
        sol.setAuxReal(T0);
    }

    if (debug>0) {
        Simulator::dbg() << "PSS analysis finshed.\n";
        ss.str("");
        ss << "Converged in " << iterIndex + 1 << " iterations.\n";
        ss << "Final worst residual ratio = " << worstRatio << "\n";
        Simulator::dbg() << ss.str();
    }

    // Enable writing for last run of shooting transient
    params.shootParams.write = params.write;
    
    solution.vector() = x0;
    pssTran_.setShootIC(x0);
    if (!pssTran_.clearTrajectory()) {
        setError(PssError::ShootingTranFailed);
        co_yield CoreState::Aborted;
    }
    // Only capture trajectory if we intend to calculate the adjoint monodromy matrix
    if (params.adjoint) {
        pssTran_.enableTrajectoryCapture();
    }
    if (!runShoot(T0)) {
        co_yield CoreState::Aborted;
    }

    // Integrate Omega backward using captured trajectory
    if (params.adjoint) {
        if ( !pssTran_.integrateAdjointMonodromy(omegaT_)) {
            setError(PssError::AdjointFailed);
            co_yield CoreState::Aborted;
        
        }
    }

    if (debug>0) {
        ss.str(""); 
        auto n = circuit.unknownCount();
        ss << "-- Monodromy --\n";
        ss << "\tPhi(T,0) =\n";
        for (decltype(n) i = 0; i < n; i++) {
            ss << "\t  [ ";
            for (decltype(n) j = 0; j < n; j++) ss << pssTran_.phiCurrent().at(i, j) << " ";
            ss << "]\n";
        }
        if (params.adjoint) {
            ss << "\tOmega(T,0) =\n";
            for (decltype(n) i = 0; i < n; i++) {
                ss << "\t  [ ";
                for (decltype(n) j = 0; j < n; j++) ss << omegaT_.at(i, j) << " ";
                ss << "]\n";
            }
        }
        Simulator::dbg() << ss.str();
    }
    
    x0_converged_ = x0;
    T0_converged_ = T0;
    co_yield CoreState::Finished;
    
}

bool PssCore::run(bool continuePrevious) {
    auto c = coroutine(continuePrevious);
    bool ok = true;
    while (!c.done()) {
        if (c.resume() == CoreState::Aborted) {
            ok = false;
            break;
        }
    }
    return ok;

}

std::tuple<bool, const DenseMatrix<double>&> PssCore::convergedAdjointMonodromy() {
    if (!params.adjoint) {
        setError(PssError::AdjointDisabled);
        return std::make_tuple(false, omegaT_);
    }
    return std::make_tuple(true, omegaT_);;
}

bool PssCore::formatError(Status& s) const {
    switch (lastPssError) {
        case PssError::NoConvergence:
            s.set(Status::Analysis,
                  "PSS failed to converge in " +
                  std::to_string(circuit.simulatorOptions().core().pss_itl) + " iterations.");
            return false;
        case PssError::SensitivityFailed:
            // Format pssTran_ error, add message
            pssTran_.formatError(s);
            s.extend("PSS sensitivity integration failed.");
            return false;
        case PssError::AdjointFailed:
            s.set(Status::Analysis, "Adjoint monodromy computation failed.");
            return false;
        case PssError::AdjointDisabled:
            s.set(Status::Analysis, "Adjoint monodromy was not computed. Set adjoint=1 before running PSS.");
            return false;
        case PssError::LinearSolveFailed:
            s.set(Status::Analysis, "PSS Newton linear solve failed.");
            return false;
        case PssError::OutputError:
            s.set(Status::Analysis, "PSS output error.");
            return false;
        case PssError::TperInvalid:
            s.set(Status::Analysis, "Period should be >0.");
            return false;
        case PssError::SingularJacobian:
            s.set(Status::Analysis, "Singular Jacobian.");
            return false;
        case PssError::StabstepInvalid:
            s.set(Status::Analysis, "Stabilization timestep must be smaller than the period.");
            return false;
        case PssError::StabilisationTranFailed:
            stabilTran_.formatError(s);
            s.extend("PSS stabilisation transient failed.");
            return false;
        case PssError::OpFailed:
            opCore_.formatError(s);
            s.extend("PSS operating point failed.");
            return false;
        case PssError::ShootingTranFailed:
            pssTran_.formatError(s);
            s.extend("PSS transient failed.");
            return false;
        case PssError::ForcesFailed: {
            auto nr = UnknownNameResolver(circuit);
            opCore_.solver().formatError(s, &nr);
            s.extend("Failed to set forces.");
            return false;
        }
        default:
            return true;
    }
}

void PssCore::dump(std::ostream& os) const {
    AnalysisCore::dump(os);
    os << "  Converged period: " << T0_converged_ << " s\n";
    os << "  Converged frequency: "
       << (T0_converged_ > 0 ? 1.0 / T0_converged_ : 0.0) << " Hz\n";
}

} // namespace NAMESPACE
